services:
  plandev_proxy:
    container_name: plandev_proxy
    depends_on:
     - "plandev_ui"
     - "hasura"
     - "plandev_gateway"
    build:
      context: proxy
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
     - "9000:9000"
    environment:
        NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
        PLANDEV_HOST: ${PLANDEV_HOST}
    networks:
      - plandev_net
  plandev_action:
    ports: !reset [ ]
  plandev_gateway:
    ports: !reset []
    environment:
      GQL_API_URL: http://hasura:8080/v1/graphql
  plandev_merlin:
    ports: !reset []
  plandev_merlin_worker_1:
    ports: !reset []
  plandev_scheduler:
    ports: !reset []
  plandev_scheduler_worker_1:
    ports: !reset []
  plandev_sequencing:
    ports: !reset []
  plandev_workspace:
    ports: !reset []
  plandev_ui:
    ports: !reset []
    environment:
      ORIGIN: https://${PLANDEV_HOST}
      PUBLIC_ACTION_CLIENT_URL: http://${PLANDEV_HOST}:27186
      PUBLIC_GATEWAY_CLIENT_URL: https://${PLANDEV_HOST}:9000
      PUBLIC_HASURA_CLIENT_URL: https://${PLANDEV_HOST}:8080/v1/graphql
      PUBLIC_HASURA_WEB_SOCKET_URL: wss://${PLANDEV_HOST}:8080/v1/graphql
      PUBLIC_WORKSPACE_CLIENT_URL: https://{PLANDEV_HOST}:28000
  hasura:
    ports: !reset []
  postgres:
    ports: !reset []
