name: Load NPM Caches
description: Load cached NPM modules for Sequencing Server and Action Server
runs:
  using: composite
  steps:
    - name: Cache Sequencing NPM Packages
      uses: actions/cache@v5
      with:
        path: ./sequencing-server/node_modules
        key: sequencing-${{ runner.os }}-${{ hashFiles('./sequencing-server/package-lock.json') }}
    - name: Cache Action NPM Packages
      uses: actions/cache@v5
      with:
        path: ./action-server/node_modules
        key: action-${{ runner.os }}-${{ hashFiles('./action-server/package-lock.json') }}
